refactor: remove module loading support

diff --git a/scripts/Makefile.modpost b/scripts/Makefile.modpost
--- a/scripts/Makefile.modpost
+++ b/scripts/Makefile.modpost
@@ -1,36 +1,9 @@
 # SPDX-License-Identifier: GPL-2.0
 # ===========================================================================
-# Module versions
+# vmlinux symbol post-processing
 # ===========================================================================
 #
-# Stage one of module building created the following:
-# a) The individual .o files used for the module
-# b) A <module>.o file which is the .o files above linked together
-# c) A <module>.mod file, listing the name of the preliminary <module>.o file,
-#    plus all .o files
-# d) modules.order, which lists all the modules
-
-# Stage 2 is handled by this file and does the following
-# 1) Find all modules listed in modules.order
-# 2) modpost is then used to
-# 3)  create one <module>.mod.c file per module
-# 4)  create one Module.symvers file with CRC for all exported symbols
-
-# Step 3 is used to place certain information in the module's ELF
-# section, including information such as:
-#   Version magic (see include/linux/vermagic.h for full details)
-#     - Kernel release
-#     - SMP is CONFIG_SMP
-#     - PREEMPT is CONFIG_PREEMPT[_RT]
-#     - GCC Version
-#   Module info
-#     - Module version (MODULE_VERSION)
-#     - Module alias'es (MODULE_ALIAS)
-#     - Module license (MODULE_LICENSE)
-#     - See include/linux/module.h for more details
-
-# Step 4 is solely used to allow module versioning in external modules,
-# where the CRC of each module is retrieved from the Module.symvers file.
+# modpost is kept for vmlinux section checks and exported symbol metadata.
 
 PHONY := __modpost
 __modpost:
@@ -41,8 +14,6 @@ include $(srctree)/scripts/Kbuild.include
 MODPOST = $(objtree)/scripts/mod/modpost
 
 modpost-args =										\
-	$(if $(CONFIG_MODULES),-M)							\
-	$(if $(CONFIG_MODVERSIONS),-m)							\
 	$(if $(CONFIG_SECTION_MISMATCH_WARN_ONLY),,-E)					\
 	$(if $(KBUILD_MODPOST_WARN),-w)							\
 	$(if $(KBUILD_NSDEPS),-d modules.nsdeps)					\
@@ -68,11 +39,6 @@ ifeq ($(KBUILD_EXTMOD),)
 
 # Generate the list of in-tree objects in vmlinux
 # ---------------------------------------------------------------------------
-
-# This is used to retrieve symbol versions generated by genksyms.
-ifdef CONFIG_MODVERSIONS
-vmlinux.symvers Module.symvers: .vmlinux.objs
-endif
 
 # Ignore libgcc.a
 # Some architectures do '$(CC) --print-libgcc-file-name' to borrow libgcc.a
@@ -131,10 +97,9 @@ endif # ($(KBUILD_EXTMOD),)
 quiet_cmd_modpost = MODPOST $@
       cmd_modpost = \
 	$(if $(missing-input), \
-		echo >&2 "WARNING: $(missing-input) is missing."; \
-		echo >&2 "         Modules may not have dependencies or modversions."; \
-		echo >&2 "         You may get many unresolved symbol errors."; \
-		echo >&2 "         You can set KBUILD_MODPOST_WARN=1 to turn errors into warning"; \
+	echo >&2 "WARNING: $(missing-input) is missing."; \
+	echo >&2 "         You may get many unresolved symbol errors."; \
+	echo >&2 "         You can set KBUILD_MODPOST_WARN=1 to turn errors into warning"; \
 		echo >&2 "         if you want to proceed at your own risk.";) \
 	$(MODPOST) $(modpost-args)
 
